### ISSUE TITLE
bytcr-rt5640 initiializes but has no sound on 4.5.1 (Arch)

### ISSUE THREAD

**Issue by parkerlreed** [plbossart/UCM#1]
I copied the bytcr-5640 folder to the ucm folder as specified, removed my old asound.state from /var/lib/alsa, and rebooted.

Upon booting back up, starting X, and running pavucontrol, I can hear the sound card initialize in my headphones. Card shows up and I can switch between speakers and headphones. Problem is on headphones I have no audio output (I cannot test speaker output as mine are broken) Tested with the slider pops in pavucontrol and with a music player application. Pavucontrol shows audio being played and the VU meter moves but no sound comes out.

Dmesg from this kernel. 
[dmesg.txt](https://github.com/plbossart/UCM/files/224230/dmesg.txt)

**Comment by plbossart** [comment]
On 4/18/16 11:32 AM, parkerlreed wrote:
> I copied the bytcr-5640 folder to the ucm folder as specified, removed
> my old asound.state from /var/lib/alsa, and rebooted.
>
> Upon booting back up, starting X, and running pavucontrol, I can hear
> the sound card initialize in my headphones. Card shows up and I can
> switch between speakers and headphones. Problem is on headphones I have
> no audio output (I cannot test speaker output as mine are broken) Tested
> with the slider pops in pavucontrol and with a music player application.
> Pavucontrol shows ausio being played an the VU meter moves but no sound
> comes out.
>
> Dmesg from this kernel.
> dmesg.txt <https://github.com/plbossart/UCM/files/224230/dmesg.txt>

Did the headphones ever work with the legacy byt-rt5640 driver? I test 
on a T100TA so not sure what could possibly cause this. Can you share 
the pulseaudio -vvv log?

**Comment by parkerlreed** [comment]
This is on a T100TA :D 

Yeah on 4.4.5 and below I used the firmware and state file from here https://github.com/T100Ubuntu/T100Ubuntu/wiki/Setup-Sound

Headphones worked after switching to them in Pulseaudio

As for a current Pulseaudio log here you go 

[pulse.txt](https://github.com/plbossart/UCM/files/224502/pulse.txt)

It says daemon startup failed but I know it wasn't running before launching it (That's been a quirk of pulse in general from what I've seen)

**Comment by plbossart** [comment]
On 4/18/16 1:49 PM, parkerlreed wrote:
> This is on a T100TA :D
>
> Yeah on 4.4.5 and below I used the firmware and state file from here
> https://github.com/T100Ubuntu/T100Ubuntu/wiki/Setup-Sound
>
> Headphones worked after switching to them in Pulseaudio
>
> As for a current Pulseaudio log here you go
>
> pulse.txt <https://github.com/plbossart/UCM/files/224502/pulse.txt>
>
> It says daemon startup failed but I know it wasn't running before
> launching it (That's been a quirk of pulse in general from what I've seen)

Weird.
can you try the patch below and record while you play. In theory this 
does a loopback in the codec, just to test that the samples reach the 
codec or is this is already dead before the analog configuration. If you 
don't see the same data in your record stream then something is wrong in 
the digital setup.

--- a/rt5640.c	2015-11-16 18:12:37.242177000 +0800
+++ b/rt5640.c	2016-02-15 10:46:01.012060000 +0800
@@ -58,6 +58,7 @@
  	{RT5640_PR_BASE + 0x20,	0x6110},
  	{RT5640_PR_BASE + 0x21,	0xe0e0},
  	{RT5640_PR_BASE + 0x23,	0x1804},
+	{RT5640_PR_BASE + 0x3a,	0x4102},
  };

  static const struct reg_default rt5640_reg[] = {

**Comment by parkerlreed** [comment]
Did you attach a file? It didn't come through on the github issue page.

**Comment by parkerlreed** [comment]
I'm also compiling 4.6 rc4 at the moment to see if that clears up any weird bugs. Will let you know.

**Comment by parkerlreed** [comment]
Same issue on 4.6rc4.r7.g95d0c42-1. Initializes but no sound. I'd be happy to try the patched file if you want to upload it somewhere first. Seems email attachments don't pass through to github.

**Comment by plbossart** [comment]
On 4/18/16 1:58 PM, parkerlreed wrote:
> Did you attach a file? It didn't come through on the github issue page.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/plbossart/UCM/issues/1#issuecomment-211529076>

inline text

--- a/rt5640.c    2015-11-16 18:12:37.242177000 +0800
+++ b/rt5640.c    2016-02-15 10:46:01.012060000 +0800
@@ -58,6 +58,7 @@
      {RT5640_PR_BASE + 0x20,    0x6110},
      {RT5640_PR_BASE + 0x21,    0xe0e0},
      {RT5640_PR_BASE + 0x23,    0x1804},
+    {RT5640_PR_BASE + 0x3a,    0x4102},
  };

  static const struct reg_default rt5640_reg[] = {

**Comment by parkerlreed** [comment]
It's not coming through :/ https://my.mixtape.moe/qfflzl.mp4

**Comment by parkerlreed** [comment]
And I view the source and it shows up. GG Github

````
<div class="email-signature-reply">--- a/rt5640.c    2015-11-16 18:12:37.242177000 +0800
+++ b/rt5640.c    2016-02-15 10:46:01.012060000 +0800
@@ -58,6 +58,7 @@
      {RT5640_PR_BASE + 0x20,    0x6110},
      {RT5640_PR_BASE + 0x21,    0xe0e0},
      {RT5640_PR_BASE + 0x23,    0x1804},
+    {RT5640_PR_BASE + 0x3a,    0x4102},
  };

  static const struct reg_default rt5640_reg[] = {</div>
</div>
````

**Comment by parkerlreed** [comment]
Is that a kernel patch?

**Comment by Boteium** [comment]
I have exactly the same problem on 4.5.2-1-ck on Asus T100TA (Arch Linux). 
I use alsa only without pulseaudio.

"mpv" complains about
[ao/alsa] Unable to set hw-parameters: Invalid argument

"speaker-test" says
Unable to set hw params for playback: Invalid argument
Setting of hwparams failed: Invalid argument

**Comment by Boteium** [comment]
same behavior on 4.5.3

Although I didn't use pulseaudio. I did test pulseaudio.
It's the same. it works on headphone only.

**Comment by plbossart** [comment]
On 5/8/16 12:41 PM, SuIông N. wrote:
> I have exactly the same problem on 4.5.2-1-ck on Asus T100TA (Arch Linux).
> I use alsa only without pulseaudio.
>
> "mpv" complains about
> [ao/alsa] Unable to set hw-parameters: Invalid argument
>
> "speaker-test" says
> Unable to set hw params for playback: Invalid argument
> Setting of hwparams failed: Invalid argument

Is this T100TA or T100TAF? The latter is known to be problematic and a 
known issue

If this is to T100TA, it works for me.

**Comment by parkerlreed** [comment]
This was on T100TA for me. I say "was" because I ended up just trading it for a better laptop. :/ Loved it to death but just couldn't deal with the quirks. @Boteium best of luck with yours.

**Comment by Boteium** [comment]
It suddenly works now. And I have no idea why.

**Comment by ntfs1984** [comment]
I have the same problem.
Installed Mint+Cinnamon. Updated firmware-intel-sound from the Debian's Stretch repository. Updated kernel to 4.6. Copied UCM folder. Did alsactl restore. But no sound.
alsaplay -L displays two soundcards;
when I'm switching between speakers and headphone in Mint's pavucontrol, I hear init, like soundcard awakened from sleep mode (a small noise);
alsamixer has a lot of volume fields, much of them are set to 0;
speaker-test is silent;
My device is Unbranded UB-15MS10, looks like a chinese copy of Asus T100.
Also, sound works under Windows 10, so this is definitely not hardware problem.

Please advice.
Thanks!

**Comment by parkerlreed** [comment]
````
Linux t100ta 4.7.2-1-ARCH #1 SMP PREEMPT Sat Aug 20 23:02:56 CEST 2016 x86_64 GNU/Linux
````

Issue persists on T100TA (Got my old one back) Pulse shows the device correctly but no sound.

**Comment by plbossart** [comment]
T100TA and T100TAF are working with my latest sound/ branch t100-taf7 which fixes known issues and the code will be merged in 4.9 if everything goes well

**Comment by parkerlreed** [comment]
Cheers! Thanks for the update.

**Comment by parkerlreed** [comment]
On that same 4.7 kernel as above I do get this spammed to dmesg for a while

````
Sep 01 00:30:22 t100ta kernel:  Baytrail Audio Port: ASoC: no backend DAIs enabled for Baytrail Audio Port
````

**Comment by plbossart** [comment]
typical symptom of the mixers not being initialized. use the UCM files or set up the routing as needed.

**Comment by youling257** [comment]
http://pastebin.com/UYqdZWbm , dmesg, still no sound

**Comment by plbossart** [comment]
[   27.021399] intel_sst_acpi 80860F28:00: Detected Baytrail-CR platform
[   27.108226] bytcr_rt5640 bytcr_rt5640: quirk DMIC1_MAP enabled
[   27.108230] bytcr_rt5640 bytcr_rt5640: quirk DMIC enabled
[   27.108233] bytcr_rt5640 bytcr_rt5640: quirk SSP0_AIF2 enabled

-> if this does not work you need to add a quirk to enable SSP0_AIF1

**Comment by youling257** [comment]
how to enable SSP0_AIF1 ?

**Comment by plbossart** [comment]
Something like this:
https://github.com/plbossart/sound/commit/07ffd5d26ec3ee0f2883e0dfa80bb5dcce267203

**Comment by youling257** [comment]
+			DMI_MATCH(DMI_BOARD_VENDOR, "TECLAST"),
+			DMI_MATCH(DMI_BOARD_NAME, "tPAD"),

what is DMI_BOARD_VENDOR and DMI_BOARD_NAME ? how to know ? my tablet onda

**Comment by plbossart** [comment]
use "dmidecode" to get all the required fields

**Comment by youling257** [comment]
BYT_RT5640_IN3_MAP
BYT_RT5640_IN1_MAP
driver_data = (unsigned long *)(BYT_RT5640_DMIC2_MAP
driver_data = (unsigned long *)(BYT_RT5640_DMIC1_MAP 
There are a lot of possibilities for my tablet.

**Comment by plbossart** [comment]
this is for capture, try to make the playback work and the only parameters are mono/stereo and SSPx-AIFy quirk

**Comment by youling257** [comment]
http://pastebin.com/W1GjqAtc , i don't know my tablet DMI_BOARD_VENDOR and DMI_BOARD_NAME

**Comment by plbossart** [comment]
http://unix.stackexchange.com/questions/75750/how-can-i-find-the-hardware-model-in-linux

**Comment by youling257** [comment]
http://pastebin.com/W1GjqAtc ,please you tell me what is my tablet DMI_BOARD_VENDOR and DMI_BOARD_NAME, i don't know

**Comment by plbossart** [comment]
BOARD_VENDOR= "Insyde"
BOARD_NAME="ONDA Tablet"

**Comment by youling257** [comment]
.callback = byt_rt5640_quirk_cb,
		.matches = {
			DMI_MATCH(DMI_BOARD_VENDOR, "Insyde"),
			DMI_MATCH(DMI_BOARD_NAME, "ONDA Tablet"),
		},
		.driver_data = (unsigned long *)(BYT_RT5640_IN3_MAP |
						 BYT_RT5640_MCLK_EN |
						 BYT_RT5640_SSP0_AIF1),

i compile kernel, it still bytcr_rt5640 bytcr_rt5640: quirk SSP0_AIF2 enabled

**Comment by youling257** [comment]
well，has sound.
.callback = byt_rt5640_quirk_cb,
		.matches = {
			DMI_MATCH(DMI_SYS_VENDOR, "Insyde"),
			DMI_MATCH(DMI_PRODUCT_NAME, "ONDA Tablet"),
		},
		.driver_data = (unsigned long *)(BYT_RT5640_IN1_MAP |
						 BYT_RT5640_MCLK_EN |
						 BYT_RT5640_SSP0_AIF1),
I compile Android x86 4.8 kernel，make it has sound, Android x86, need /system/etc/alsa/bytcrrt5640.state , it is /var/lib/alsa/asound.state，
Android x86 neeedn't /usr/share/alsa/ucm/bytcr-rt5640.

today，I compile Ubuntu 4.8 kernel and Android x86 4.8

**Comment by plbossart** [comment]
send a patch with your signoff to me or alsa-devel if you want this upstream

**Comment by youling257** [comment]
also need https://groups.google.com/group/android-x86/attach/d1ffc290d6d56/alsa_bytcr_andx86.zip?part=0.1&authuser=0&view=1 ，alsa_cr_spk.sh，alsa_cr_hp.sh，Switching headphones and speakers

**Comment by youling257** [comment]
[bytcr_5640.c.zip](https://github.com/plbossart/UCM/files/459676/bytcr_5640.c.zip)
I don't know how to make patch, gave you bytcr_5640.c

**Comment by plbossart** [comment]
git add bytcr_5640.c
git commit bytcr_5640.c
git format-patch --signoff HEAD^

**Comment by youling257** [comment]
[0001-onda-tablet-sound.zip](https://github.com/plbossart/UCM/files/460487/0001-onda-tablet-sound.zip)

patch

**Comment by youling257** [comment]
[0001-sound.zip](https://github.com/plbossart/UCM/files/465241/0001-sound.zip)

should use this patch

**Comment by parkerlreed** [comment]
Compiling 4.8 from git now. Patch succeeded.

**Comment by parkerlreed** [comment]
Umm

````
 CC [M]  net/llc/llc_pdu.o
  CC [M]  net/ipv6/ila/ila_xlat.o
  CC [M]  fs/ocfs2/slot_map.o
  CC [M]  net/mac80211/status.o
  LD [M]  sound/pci/snd-bt87x.o
  CC [M]  drivers/bluetooth/btsdio.o
  LD [M]  sound/pci/snd-cmipci.o
  CC [M]  fs/ocfs2/suballoc.o
  LD [M]  sound/pci/ymfpci/snd-ymfpci.o
  LD [M]  sound/pci/snd-cs4281.o
  LD [M]  sound/pci/snd-ens1370.o
  LD [M]  sound/pci/snd-ens1371.o
  LD [M]  sound/pci/snd-es1938.o
  CC [M]  net/llc/llc_sap.o
  LD [M]  sound/pci/snd-es1968.o
  CC [M]  fs/ocfs2/super.o
  LD [M]  sound/pci/snd-fm801.o
  LD [M]  sound/pci/snd-intel8x0.o
  CC [M]  net/ipv4/esp4.o
  LD [M]  sound/pci/snd-intel8x0m.o
  LD [M]  sound/pci/snd-maestro3.o
  CC [M]  net/ipv4/netfilter/nf_nat_pptp.o
  LD [M]  sound/pci/snd-rme32.o
  LD [M]  net/ipv6/ila/ila.o
  LD [M]  sound/pci/snd-rme96.o
  CC [M]  drivers/bluetooth/btintel.o
  LD [M]  sound/pci/snd-sonicvibes.o
  LD      net/ipv6/netfilter/built-in.o
  LD [M]  sound/pci/snd-via82xx.o
  CC [M]  net/ipv6/netfilter/ip6_tables.o
  LD [M]  sound/pci/snd-via82xx-modem.o
make: *** [Makefile:968: sound] Error 2
make: *** Waiting for unfinished jobs....
  CC [M]  net/llc/llc_s_ac.o
  CC [M]  net/ipv6/netfilter/ip6table_filter.o
  CC [M]  fs/ocfs2/symlink.o
  CC [M]  net/ipv4/netfilter/nf_nat_snmp_basic.o
  CC [M]  net/ipv4/ipcomp.o
  CC [M]  fs/ocfs2/sysfile.o
  CC [M]  net/mac80211/driver-ops.o
  CC [M]  net/llc/llc_s_ev.o
  CC [M]  drivers/bluetooth/ath3k.o
  CC [M]  net/ipv6/netfilter/ip6table_mangle.o
  CC [M]  net/ipv4/netfilter/nf_nat_masquerade_ipv4.o
  CC [M]  net/ipv6/netfilter/ip6table_raw.o
  CC [M]  fs/ocfs2/uptodate.o
  CC [M]  net/ipv4/xfrm4_tunnel.o
  CC [M]  net/llc/llc_s_st.o
  CC [M]  net/ipv6/netfilter/ip6table_security.o
  CC [M]  drivers/bluetooth/btmrvl_main.o
  CC [M]  net/ipv6/netfilter/ip6table_nat.o
  CC [M]  net/ipv6/netfilter/nf_conntrack_l3proto_ipv6.o
  CC [M]  net/mac80211/sta_info.o
  CC [M]  net/ipv4/xfrm4_mode_beet.o
  CC [M]  net/llc/af_llc.o
  CC [M]  net/ipv4/netfilter/nf_nat_proto_gre.o
  CC [M]  net/llc/llc_station.o
  CC [M]  net/ipv6/netfilter/nf_conntrack_proto_icmpv6.o
  CC [M]  net/ipv6/netfilter/nf_nat_l3proto_ipv6.o
````

It still hasn't quit out due to so many threads. I'll update with error.

**Comment by parkerlreed** [comment]
Here's my current bytcr_rt5640.c http://ix.io/1nXP

(Still waiting on kernel compile to finish/error out)

**Comment by parkerlreed** [comment]
Well fuck me sideways. Tried just booting my regular 4.8 compile and it doesnt even boot on the T100TA. Fails at the start job for dev-mmcblk0p2. So even if the sound patch worked I wouldnt be able to use it unless I patched an older kernel version.

**Comment by youling257** [comment]
git clone https://github.com/torvalds/linux.git
  git remote add sound https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git
  git fetch sound
  git merge sound/topic/intel
  patch -p1 > 13-17-clk-x86-Add-Atom-PMC-platform-clocks.patch
https://patchwork.kernel.org/patch/9277989/

did you merge sound ?
0001-sound.zip for my tablet, you needn't
now, please you dmesg .

**Comment by parkerlreed** [comment]
I didn't merge sound because this is the first time you have mentioned that...

**Comment by parkerlreed** [comment]
@youling257 http://ix.io/1ooH

Pulseaudio daemon starts but pavucontrol just freezes when launched.

**Comment by youling257** [comment]
try these files ,https://github.com/burzumishi/linux-baytrail-flexx10/tree/master/sound/alsa_ctrl , alsa_cr_hp.sh，alsa_cr_spk.sh，Switching headphones and speakers

**Comment by parkerlreed** [comment]
Yes, T100TA. Will try out the files.

**Comment by parkerlreed** [comment]
THAT WORKED!! (alsa_cr_spk.sh)

For reference: Asus T100TA, 4.8 kernel from git, NOT using the UCM files from this repo.

**Comment by youling257** [comment]
@plbossart  Headset Mic and Internal Mic can't work

**Comment by speculatrix** [comment]
just wondering if this still works with kernel 4.12-rc2 on Baytrail?

**Comment by maferv** [comment]
@youling257 thank you for your scripts

**Comment by sleeply4cat** [comment]
> try these files ,https://github.com/burzumishi/linux-baytrail-flexx10/tree/master/sound/alsa_ctrl , alsa_cr_hp.sh，alsa_cr_spk.sh，Switching headphones and speakers
> your tablet , t100ta ?

files are gone

**Comment by kousu** [comment]
@sleeply4cat , it looks like there's luckily a mirror at https://groups.google.com/group/android-x86/attach/d1ffc290d6d56/alsa_bytcr_andx86.zip?part=0.1&authuser=0&view=1.

I'm attaching them here too.
[alsa_bytcr_andx86.zip](https://github.com/plbossart/UCM/files/3501885/alsa_bytcr_andx86.zip)

I had to patch them because those versions are for Android, I guess; I added

```
set -xe
alias alsa_amixer=amixer
```

to the top of each script, then I ran

```
sh alsa_cr.sh ; sh alsa_cr_spk.sh 
```

Unfortunately, **this did not solve all the sound problems with my tablet**. They made it less screechy and I can make out music played with `mpv` now, but it's very quiet. Maybe these scripts are missing something because they are for Androids, or maybe it's because I have a knock-off MDG Baytrail tablet and it has further quirks. I'll keep you posted. I'm running Arch with kernel 5.2.8 so I would have hoped things got fixed by now but no dice I guess.

**Comment by kousu** [comment]
I figured out why the sound was so quiet: for some reason `mpv` was trying to interpret my test files in the wrong format:

This played too quietly:

```
$ mpv techno.mp3 
Playing: techno.mp3
 (+) Audio --aid=1 (mp3 2ch 44100Hz)
File tags:
 Artist: Bruno Rodrigo
 Comment: Bleep Bloop Records
 Date: 2009
 Genre: Dance
 Title: Drugs Of Choice - N-Junior Rem
 Track: 1
AO: [alsa] 48000Hz stereo 2ch float
A: 00:00:04 / 00:05:33 (1%)


Exiting... (Quit)
```

whereas telling it explicitly to use 16-bit integer format fixed it:

```
$ mpv --af=format=s16 techno.mp3 
Playing: techno.mp3
 (+) Audio --aid=1 (mp3 2ch 44100Hz)
File tags:
 Artist: Bruno Rodrigo
 Comment: Bleep Bloop Records
 Date: 2009
 Genre: Dance
 Title: Drugs Of Choice - N-Junior Rem
 Track: 1
AO: [alsa] 48000Hz stereo 2ch s16
A: 00:00:22 / 00:05:33 (6%)


Exiting... (Quit)
```

also

```
$ mpg123 techno.mp3 
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
	version 1.25.11; written and copyright by Michael Hipp and others
	free software (LGPL) without any warranty but with best wishes


Terminal control enabled, press 'h' for listing of keys and functions.

Playing MPEG stream 1 of 1: techno.mp3 ...

MPEG 1.0 L III cbr320 44100 j-s

Title:   Drugs Of Choice - N-Junior Rem                                                           Artist: Bruno Rodrigo                                                                           
Comment: Bleep Bloop Records                                                                      Album:                                                                                          
Year:    2009                                                                                     Genre:  Dance                                                                                   

```

worked directly.

**Comment by kousu** [comment]
@sleeply4cat , I also discovered while poking around that `alsa-lib` now comes with those scripts inlined:

```
$ ls /usr/share/alsa/ucm/codecs/rt5640/
DigitalMics.conf  EnableSeq.conf  HeadPhones.conf  HeadsetMic.conf  IN1-InternalMic.conf  IN3-InternalMic.conf  MonoSpeaker.conf  Speaker.conf
```

I haven't figured out how to use them yet though. `alsamixer` doesn't seem to expose them. Maybe one needs pulseaudio running to be able to use these alsa configs? I hope not. What I've done so far is read them manually:

```
$ cat /usr/share/alsa/ucm/codecs/rt5640/HeadPhones.conf 
SectionDevice."Headphones" {
	Comment "Headphones"

	ConflictingDevice [
		"Speaker"
		"MonoSpeaker"
	]

	EnableSequence [
		cdev "hw:bytcrrt5640"

 		cset "name='DAC MIXL INF1 Switch'  on"
 		cset "name='DAC MIXR INF1 Switch'  on"
 		cset "name='Stereo DAC MIXL DAC L1 Switch'  on"
 		cset "name='Stereo DAC MIXR DAC R1 Switch'  on"
		cset "name='Stereo DAC MIXL DAC L2 Switch'  on"
 		cset "name='Stereo DAC MIXR DAC R2 Switch'  on"
 		cset "name='HPO MIX HPVOL Switch'  on"
 		cset "name='Headphone Switch'  on"
		cset "name='HP Channel Switch' on"
 		cset "name='Speaker Switch' off"
		cset "name='HP L Playback Switch' on"
		cset "name='HP R Playback Switch' on"
		cset "name='HP Playback Volume' 29"

	]

	DisableSequence [
		cdev "hw:bytcrrt5640"
		cset "name='Headphone Switch' off"
		cset "name='HP Channel Switch' off"
		cset "name='HP L Playback Switch' off"
		cset "name='HP R Playback Switch' off"
		cset "name='HP Playback Volume' 0"
	]

	Value {
		PlaybackChannels "2"
		JackControl "Headphone Jack"
	}
}
```

and then followed the instructions in them with `alsamixer`; you could also recreate a script by pasting `amixer` in front of each line, eg:

```
...
amixer		cset name='HP L Playback Switch' on
amixer		cset name='HP R Playback Switch' on
amixer		cset name='HP Playback Volume' 29
```
