### ISSUE TITLE
No sound on rt5651

### ISSUE THREAD

**Issue by Ilia1** [plbossart/UCM#10]
Help please. I do not know what the problem is. There are three devices for audio output: speaker, headphones and HDMI. Like the order of the devices correctly configured, through the alsamixer headphones completely disabled.

>  cat /proc/asound/modules
 0 snd_soc_sst_bytcr_rt5651
 1 snd_hdmi_lpe_audio

> dmesg |grep rt5651
[   10.505700] snd_soc_sst_bytcr_rt5651: unknown parameter 'index' ignored
[   10.528578] bytcr_rt5651 bytcr_rt5651: snd-soc-dummy-dai <-> media-cpu-dai mapping ok
[   10.528654] bytcr_rt5651 bytcr_rt5651: snd-soc-dummy-dai <-> deepbuffer-cpu-dai mapping ok
[   10.528784] bytcr_rt5651 bytcr_rt5651: rt5651-aif1 <-> ssp2-port mapping ok
[   10.529001] rt5651 i2c-10EC5651:00: ASoC: mux INL1 Mux has no paths
[   10.529014] rt5651 i2c-10EC5651:00: ASoC: mux INR1 Mux has no paths
[   10.529023] rt5651 i2c-10EC5651:00: ASoC: mux INL2 Mux has no paths
[   10.529032] rt5651 i2c-10EC5651:00: ASoC: mux INR2 Mux has no paths

**Comment by plbossart** [comment]
this message is at the codec driver level and i don't have the information on how to solve it. report the issue on alsa-devel or file a bug at bugzilla.kernel.org (component ALSA) with Bard Liao and me in copy.

**Comment by gsantner** [comment]
On my device headphones do work. HDMI and speakers are not recognized. Pulseaudio crashes a lot using the configs too

**Comment by Ilia1** [comment]
https://bugzilla.kernel.org/show_bug.cgi?id=196193
