### ISSUE TITLE
chtrt5645: crackling sound on background

### ISSUE THREAD

**Issue by stockmind** [plbossart/UCM#11]
Hi there,

I successfully installed your UCM driver for following device:
chtrt5645 on a GPD Pocket mini-laptop. (Atom x7-8750 Cherry Trail, Realtek ALC5645, built-in stereo speaker, microphone, 3.5mm headset jack)

I'm using 4.12 kernel compiled from here https://github.com/jwrdegoede/linux-sunxi

Audio works but i can hear a noisy "crackling" sound on background.
It sounds like the background noise of a bonfire. Weak but is there. 
On high volume i can hear it clearly.
This doesn't happen on Windows.

There is something i could provide to help debugging?
There is something i need to check?

Thank you!

**Comment by plbossart** [comment]
do you hear the noise on the headphone, speaker or both outputs?
I do have noise on the headphone but things work fine with the speakers on my Asus T100 HA

**Comment by stockmind** [comment]
Speakers for sure, not sure about headphones. 
Will test it out shortly.

**Comment by stockmind** [comment]
Headphones doesn't work on 4.12 (some weak noises randomly but no audio), but works on 4.13.
The crackling noise is on both on 4.13, speakers and headphones.

**Comment by plbossart** [comment]
this could be due to a bad set of ALSA controls or to a bad kernel-level configuration. You could try to play with alsamixer to try to see if you come up with some indications of better audio (be careful, this could blow your speakers so use low volume). If nothing works, it's likely the kernel configuration with things like voltages not well configured - you would need to open a bug on bugzilla.kernel.org and copy me and Bard Liao at Realtek

**Comment by stockmind** [comment]
Just tried to play around with volumes and some other setting, just randomly actions while listening to some music just to try to see if something changes. I'm not an expert and lot of the acronyms in mixer doesn't mean anything to me. Cannot get rid of the crackling noise, neither lower it. I've tried also muting almost everything and unmute one-by-one. 
I've tried the audio-test from Sound Settings in System Settings of Unity. Audio works only when pressing "Left" button. "Right" doesn't play any sound, don't know if it can help figure out the problem.
Will check other bug related to audio driver and attach required files for debug.
Thanks

**Comment by plbossart** [comment]
some platforms only have a mono speaker, that could explain your setup. You'd need to route the route data to the left (see example in the rt5640 case)

**Comment by stockmind** [comment]
It seems that the bug is already open: https://bugzilla.kernel.org/show_bug.cgi?id=196351
How can i add you and Bard Liao? thanks!

**Comment by plbossart** [comment]
i added Bard on the bugzilla, let's continue the discussion there.
