### ISSUE TITLE
byt-max98090 mixer levels change

### ISSUE THREAD

**Issue by duffydack** [plbossart/UCM#21]
Toshiba CB2 (baytrail max98090) using archlinux and custom kernel (because legacy baytrail sound driver).  Using the byt-max98090 UCM changes how my mixers work.  Previously I'd adjust pulses 'Master' and it would also adjust the 'Speaker' mixer in alsa (or headphone mixer if using headphones), 45-50% my normal listening levels.  The levels would also keep between reboots.  With these UCM files however, after removing the old asound.state and rebooting, the pulse Master is set to 100, and alsa Speaker is 27, and output is very low.  I have to set Master to normal 45-50 and then adjust Speaker to 100 (headphones too when using them) to get the same level of output.  The problem is, Master is saved (at 45-50) but the speaker mixer is always set to 27 on boot, meaning I need to manually adjust to 100 every time.  Tried alsactl store, but no change.  Any ideas?

The UCM files have helped a little with sound distortion issues though (PLL unlock, garbled output) which my machine suffers from.
(as a temp fix I have added a script to profile.d to set amixer values.)

**Comment by plbossart** [comment]
if you know what mixer value you need, just add it to the UCM file.
I try to limit the dependency on alsactl, it doesn't state what is default and what is set on purpose so it's a mess to manage.

**Comment by duffydack** [comment]
_Ugh_, didn't think of that.  
cset "name='Speaker Volume' 100%" does the trick.  thanks.
I'm using 4.15rc1 now btw, nice to know adding baytrail to chtmax98090 works, finally.  I'll be able to use my dists stock kernel again.
