### ISSUE TITLE
Sound is disables after Speakers <-> Headphones switches [bytcr-rt5640]

### ISSUE THREAD

**Issue by DX37** [plbossart/UCM#3]
It's `bytcr-rt5640` soundcard.
After re-enabling profile, sound is back again.

**Comment by plbossart** [comment]
would you mind describing the issue in more details, I don't understand the sequence that leads to the issue nor what you mean by 're-enabling profile'
Also is this using the mono or regular speakers?

**Comment by DX37** [comment]
> Also is this using the mono or regular speakers?

Both.
For example, I listen music by using speakers. When I switching to Headphones through `pavucontrol` mixer, sound is gone. Buy when I switch profile to Disabled and back to `Play HiFi`, then sound continue to play.

**Comment by plbossart** [comment]
I am using the regular sound control panel that comes in Ubuntu and Fedora and I have no such issues.

**Comment by nrndda** [comment]
Same happens using `pactl set-sink-port ..`. Sound restores itself after awhile.
Linux 4.9.13, pulseaudio 10.0.

**Comment by plbossart** [comment]
looks like a pulse audio issue more than a UCM file issue really...

**Comment by DX37** [comment]
Ok, that's weird, but I think I shouldn't do `alsactl store` or something, but now it works normal.
But now I confirm #2 issue.
