### ISSUE TITLE
bytcr-rt5640 does not work on Acer One S1002 2-in-1 Tablet

### ISSUE THREAD

**Issue by crank123** [plbossart/UCM#5]
I have an Acer One S1002 2-in-1 tablet. I have had some driver issues with several devices, though a few are fixed. I had looked around for a solution to my sound, and it ultimately lead me here. There is one problem, however. 
![screenshot from 2017-03-07 18-23-31](https://cloud.githubusercontent.com/assets/8679113/23682713/3a9bb26e-0363-11e7-84a8-cec82983692a.png)
It clearly recognizes the device, however, I get no sound, it doesn't recognize whether or not I have headphones in or not, and I cannot use HDMI audio. I ran dmesg, and this was the output [dmesg.txt](https://github.com/plbossart/UCM/files/826143/dmesg.txt)

**Comment by dantob** [comment]
Grab a newer kernel, 4.11RC1 is the first to properly setup my hardware without external patches
http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.11-rc1/

**Comment by crank123** [comment]
Will try. About to restart with new kernel. Thank you!

**Comment by crank123** [comment]
It now recognizes another possible output, bit still not audio.
This is my [dmesg](https://github.com/plbossart/UCM/files/828702/dmesg.txt)

**Comment by dantob** [comment]
Try the newer firmware package too http://packages.ubuntu.com/zesty/all/linux-firmware/download

**Comment by crank123** [comment]
Okay. My kernel broke. So, I am going to reinstall, but once I do, I will let you know how it goes. :) Thank you!

**Comment by nicman23** [comment]
had the same thing happen to me. fixed with firmware from git.

**Comment by crank123** [comment]
Okay, when I did a fresh install, and then installed kernel 4.11rc2, then finally the UCM files, it worked perfectly. Thank you!
