### ISSUE TITLE
No sound device detected bytcr-5640

### ISSUE THREAD

**Issue by aericktoes** [plbossart/UCM#59]
I have a Dell Venue 11 Pro 5130 and I copied the UCM files, but no sound device is detected in. It's running Manjaro KDE. dmesg is filled with the following:
`baytrail Audio Port: ASoC: no backend DAIs enabled for Baytrail Audio Port`
This is repeated hundreds of times. Is there any way to have this work?

**Comment by plbossart** [comment]
I no longer maintain those files, use the official ones in alsa-lib
