### ISSUE TITLE
PulseAudio fails and sound issues on Arch mainline (4.11.0) kernel

### ISSUE THREAD

**Issue by dodslaser** [plbossart/UCM#6]
I'm using the provided UCMs on my Asus T100 running ArchLinux with the mainline kernel (4.11.0-mainline). By default theres no sound at all. PulseAudio fails with `snd_pcm_hw_params_set_buffer_size_near() failed: Invalid argument`.

Using the scripts at from [here](https://github.com/burzumishi/linux-baytrail-flexx10/tree/master/sound/alsa_ctrl) I can get sound, but it is way too fast and high pitched. The PulseAudio server still won't start.

I'm using the firmware provided by the `linux-firmware` package.

I had sound working perfectly (apart from having to switch output manually) in the default Arch kernel (4.10) using your UCMs and the above scripts.

Is there a fix for this or do I have to go back to 4.10?

**Comment by plbossart** [comment]
4.11 works for me with unmodified UCM scripts. There is a known issue with PulseAudio + LPE  HDMI but you can blacklist that driver.

**Comment by dodslaser** [comment]
@plbossart Would that affect the output on the other devices?
