### ISSUE TITLE
No sound on AMICorporation-NarrowBox4K-TobefilledbyO.E.M.-CherryTrailCR (bytchtnocodec)

### ISSUE THREAD

**Issue by q4z1** [plbossart/UCM#8]
Hi there,

I successfully installed your UCM driver for following device:

` 1 [bytchtnocodec  ]: bytcht-nocodec - bytcht-nocodec
                      AMICorporation-NarrowBox4K-TobefilledbyO.E.M.-CherryTrailCR`

Now it is listed in alsa and pulseaudio too. But I do not listen any sound on the head-phone jack - hdmi only.
I checked volume with alsamixer and it is set to 0 - and I cannot adjust it there.

As I'm not very firm with linux and audio, I'd like to ask you or anybody else here, if you can help me? Any alsa file to edit maybe?

I'm using the Narrowbox as a standalone Kodi mediacenter btw.
		
Thank you and kind regards.

**Comment by plbossart** [comment]
the -nocodec option is to be used when you have a connector and want to look at electrical signals coming out. You should not use it if you expect sound playback and should disable it in your kernel config. I know Ubuntu selected this option by mistake but that's been corrected.

**Comment by q4z1** [comment]
Hi Pierre,

thanks for your reply and a first direction.

I am running ubuntu 16.04. with kernel v4.12-rc5 from ubuntu kernel ppa and linux-firmware_1.164_all.deb.

I now downloaded sources from git, checked config and disabled `CONFIG_SND_SOC_INTEL_BYT_CHT_NOCODEC_MACH`.

I also found a hint in `sound/soc/intel/atom/sst/sst_acpi.c` whichs says at line 506:

`#if IS_ENABLED(CONFIG_SND_SOC_INTEL_BYT_CHT_NOCODEC_MACH)
	/*
	 * This is always last in the table so that it is selected only when
	 * enabled explicitly and there is no codec-related information in SSDT
	 */
	{"80860F28", "bytcht_nocodec", "intel/fw_sst_0f28.bin", "bytcht_nocodec", NULL,
						&byt_rvp_platform_data },
#endif`

... can it be, that my device does not give any known codec-related information in SSDT?

Anyway: I'm just compiling the kernel with the new config - so maybe it works after booting this kernel.

**Comment by plbossart** [comment]
if it doesn't work, file a bug on bugzilla.kernel.org  (attached DSDT and alas-info.sh log)

**Comment by q4z1** [comment]
It did not work - and after some deeper reading I found the reason: Takashi Iwai propably coded a driver for hdmi audio output only - not supporting audio output on the headphone-jack on linux.
