### ISSUE TITLE
Semi-working (buggy) audio with rt5672

### ISSUE THREAD

**Issue by RussianNeuroMancer** [plbossart/UCM#9]
Hello!

With UCM config from https://bugzilla.kernel.org/show_bug.cgi?id=96691#c46 I get 

1. When I playback audio only to left channel - left speaker playback audio.
2. When I playback audio only to right channel - there is silence.
3. Left headphone playback audio from left and right channels, but audio from left channels seems like a bit louder. At the end of audio playback there is crackling sound.
4. Right headphone playback audio from left and right channels, but audio from right channels seems like a bit louder. At the end of audio playback there is crackling sound.
5. Headset microphone is not listed in input sources.
6. Internal microphone is doesn't record anything.
7. No automatic jack detection, so no automatic switch between speakers and headphones/headset.
8. In headphones quiet sounds seems like louder, and for some reason especially voices is always quieter (for example in song - music is always louder than signer voice).

Upstream report: https://bugzilla.kernel.org/show_bug.cgi?id=195195#c1

**Comment by RussianNeuroMancer** [comment]
UCM: https://bugzilla.kernel.org/show_bug.cgi?id=96691#c88

regmap: https://bugzilla.kernel.org/show_bug.cgi?id=96691#c72

**Comment by plbossart** [comment]
you keep reporting issues that I can't reproduce and don't provide any fix or even hint of the root cause. Not sure why you expect from me here.

**Comment by RussianNeuroMancer** [comment]
> you keep reporting issues that I can't reproduce 

For me it's reproducible on two Dell 5855 tablets. Few other people with Dell 5855 can reproduce it too. 

> and don't provide any fix or even hint of the root cause

That simply because I am not audio driver developer, and not even developer. 

> Not sure why you expect from me here.

I guess you could request more data about this particular device from Realtek or Dell (I not sure if this possible, but maybe?) Or, if this can help, I can send you Dell 5855 as gift, no strings attached.

**Comment by RussianNeuroMancer** [comment]
Closed as it tracking in upstream bugtracker.
